Check limb swing motion has been finished at the end of ConfigMotion if exitWhenLimbSwingFinished is true
isri-aist/MultiContactController pull request #10
Opened 2023-10-19 04:15 UTC by orikuma

Problem:
`ConfigMotionState::run()` returns true when the commands stacked in managers become empty, but it does not consider the motion is executing or not. Therefore, the state can exit before the last swing motion has finished.

Solution:
I added `exitWhenLimbSwingFinished` option in configs for ConfigMotionState. If it is true,  `ConfigMotionState::run()` returns false until all swing motions in LimbMangerSet have finished.

2023-10-19 11:47 UTC, gergondet requested changes
Other than keeping the existing behavior is there any real use to not waiting on the execution to finish? (afaik most use of this controller only have a single motion configured

2023-10-19 11:47 UTC, gergondet commented on src/states/ConfigMotionState.cpp
> +  return limbCofingsFinshed && taskConfigList_.empty() && collisionConfigList_.empty();
```suggestion
  return !ctl().limbManagerSet_->contactCommandStacked() && taskConfigList_.empty() && collisionConfigList_.empty() && (!exitWhenLimbSwingFinished_ || !ctl().limbManagerSet_->isExecutingLimbSwing());
```
(should look nicer after formatting)

2023-10-23 02:51 UTC, orikuma commented on src/states/ConfigMotionState.cpp
> +  return limbCofingsFinshed && taskConfigList_.empty() && collisionConfigList_.empty();
Thank you for review. I refactored it.

2023-10-23 03:00 UTC, orikuma commented
> Other than keeping the existing behavior is there any real use to not waiting on the execution to finish?
I put `exitWhenLimbSwingFinished_` just for backward compatibility. Currently the motion is assumed to move one limb at once.

2024-04-11 07:19 UTC, mmurooka approved these changes
Thank you for the PR! Some small comments.

2024-04-11 07:19 UTC, mmurooka commented on src/LimbManagerSet.cpp
> +    const auto & contactCommandList = limbManagerKV.second->contactCommandList();
This line seems unnecessary.

2024-04-11 07:19 UTC, mmurooka commented on src/states/ConfigMotionState.cpp
> +  if(config_.has("configs") && config_("configs").has("exitWhenLimbSwingFinished"))
Sorry, you don't need to change it as I wrote in the following comment.

~~Same as https://github.com/isri-aist/MultiContactController/pull/7/files#r1560534133~~

2024-04-12 03:17 UTC, orikuma commented on src/LimbManagerSet.cpp
> +    const auto & contactCommandList = limbManagerKV.second->contactCommandList();
Fixed in 97b00dfd70369e541cd9cdbbbcf6739cc1a205f9

2024-04-13 05:40 UTC, closed without merging